"""create tables

Revision ID: 190753d7eabf
Revises: 
Create Date: 2023-07-04 16:32:23.448688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '190753d7eabf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('current_user_language',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('current_lang_code', sa.String(length=2), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('user_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('source_lang_code', sa.String(length=2), nullable=False),
    sa.Column('text', sa.String(length=10000), nullable=False),
    sa.Column('target_lang_code', sa.String(length=2), nullable=False),
    sa.Column('translated_text', sa.String(length=10000), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_history')
    op.drop_table('current_user_language')
    # ### end Alembic commands ###
